### ISSUE TITLE
Add page url to system events as additional data

### ISSUE THREAD

**Issue by NejcZdovc** [blotoutio/sdk-android#24]
We should add page url in additional data for the following events:

sdk_start
visibility_visible
visibility_hidden

**Comment by nitinblotout** [comment]
Is it page_title ? As mentioned in the [SDK API document](https://docs.google.com/document/d/1AcNlRJULHmd7m1FuCmsj69DTSasENPjHUMzk3WHPDTc/edit#)

**Comment by NejcZdovc** [comment]
correct
